language: python
python:
  - "2.7"
install:
  - make deps
service:
  - docker
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: radiant-woodland-30345
  api_key: ${HEROKU_API_KEY}
